### ISSUE TITLE
support vscode themes

### ISSUE THREAD

**Issue by jscool346** [Aaron00101010/vscode-http-client#1]
Its a great extension. Thanks for this

Few suggestions:

- remove view background hard-coded white color, so it will pickup theme color. 
- same for button and inputs, remove hard-coded white color
- Create gif in dark mode on github page.
- response content color highlighting for json etc..

**Comment by Aaron00101010** [comment]
thanks for your feedback, these suggestions are useful. I would improve the user experience in the dark theme.
